TOP = ..

include $(TOP)/configure/CONFIG

DB += scifi_temperature.template
DB += scifi_bias.template
DB += scifi_threshold.template
DB += scifi_mask.template

# DB += tof.template

include $(TOP)/configure/RULES