TOP = ..

include $(TOP)/configure/CONFIG

DB += scifi_temperature.template
DB += scifi_bias.template
DB += scifi_threshold.template
DB += scifi_mask.template

DB += plsci.template

DB += music_adc_ch.template
DB += music_hv.template

include $(TOP)/configure/RULES