#!/usr/bin/env python3

from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path


REQUIRED_COLUMNS = {
    "CHAMBER",
    "SCIFI_NUMBER",
    "SFP",
    "DEV",
}

Board = tuple[str, int, int, int]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate SciFi threshold waveform substitutions."
    )

    parser.add_argument(
        "--input",
        type=Path,
        default=Path("data/scifi_threshold.csv"),
        help="Input CSV containing one row per board",
    )

    parser.add_argument(
        "--output",
        type=Path,
        default=Path("db/generated/scifi_threshold.substitutions"),
        help="Generated substitutions file",
    )

    parser.add_argument(
        "--template",
        default="db/templates/scifi_threshold.template",
        help="EPICS database template path",
    )

    return parser.parse_args()


def parse_non_negative_integer(
    value: str | None,
    column: str,
    line_number: int,
) -> int:
    text = (value or "").strip()

    try:
        number = int(text)
    except ValueError as exc:
        raise ValueError(
            f"Line {line_number}: {column} must be an integer, "
            f"got {text!r}"
        ) from exc

    if number < 0:
        raise ValueError(
            f"Line {line_number}: {column} cannot be negative"
        )

    return number


def read_boards(csv_path: Path) -> list[Board]:
    if not csv_path.is_file():
        raise FileNotFoundError(f"Input CSV not found: {csv_path}")

    boards: set[Board] = set()

    with csv_path.open("r", encoding="utf-8", newline="") as stream:
        reader = csv.DictReader(stream)

        if reader.fieldnames is None:
            raise ValueError("CSV file does not contain a header")

        normalized_headers = {
            header.strip() for header in reader.fieldnames
        }

        missing_columns = REQUIRED_COLUMNS - normalized_headers

        if missing_columns:
            raise ValueError(
                "Missing required CSV columns: "
                + ", ".join(sorted(missing_columns))
            )

        for line_number, row in enumerate(reader, start=2):
            chamber = (row.get("CHAMBER") or "").strip().upper()

            if not chamber:
                raise ValueError(
                    f"Line {line_number}: CHAMBER is empty"
                )

            scifi_number = parse_non_negative_integer(
                row.get("SCIFI_NUMBER"),
                "SCIFI_NUMBER",
                line_number,
            )

            sfp = parse_non_negative_integer(
                row.get("SFP"),
                "SFP",
                line_number,
            )

            dev = parse_non_negative_integer(
                row.get("DEV"),
                "DEV",
                line_number,
            )

            board = (
                chamber,
                scifi_number,
                sfp,
                dev,
            )

            if board in boards:
                raise ValueError(
                    f"Line {line_number}: duplicate board "
                    f"{chamber} SCIFI{scifi_number} SFP{sfp} DEV{dev}"
                )

            boards.add(board)

    if not boards:
        raise ValueError("No board definitions found in the CSV file")

    return sorted(
        boards,
        key=lambda board: (
            board[0],
            board[1],
            board[2],
            board[3],
        ),
    )


def write_substitutions(
    output_path: Path,
    template_path: str,
    source_path: Path,
    boards: list[Board],
) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "# AUTO-GENERATED FILE - DO NOT EDIT",
        "# Generated by scripts/generate_scifi_threshold_substitutions.py",
        f"# Source: {source_path}",
        f"# Boards: {len(boards)}",
        f"# Threshold channels: {len(boards) * 128}",
        "#",
        "# P is supplied by dbLoadTemplate() in st.cmd.",
        "",
        f'file "{template_path}"',
        "{",
        "    pattern",
        "    {",
        "        CHAMBER,ID,SFP,DEV",
        "    }",
        "",
    ]

    for chamber, scifi_number, sfp, dev in boards:
        lines.append(
            f"    {{ {chamber},{scifi_number},{sfp},{dev} }}"
        )

    lines.extend(
        [
            "}",
            "",
        ]
    )

    output_path.write_text(
        "\n".join(lines),
        encoding="utf-8",
    )


def main() -> int:
    args = parse_args()

    try:
        boards = read_boards(args.input)

        write_substitutions(
            output_path=args.output,
            template_path=args.template,
            source_path=args.input,
            boards=boards,
        )

    except (OSError, ValueError) as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1

    print(f"Input boards: {len(boards)}")
    print(f"Generated waveform PVs: {len(boards)}")
    print(f"Total threshold channels: {len(boards) * 128}")
    print(f"Generated: {args.output}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())